###
POST http://localhost:3100/posts/seed
###
http://localhost:3100/posts
###
http://localhost:3100/
###
POST http://localhost:3100/posts
Content-Type: application/json
    
    {
        "userHandle": "@uruhara_kisuke",
        "firstName": "Uruhara",
        "lastName": "Kisuke",
        "profilePic": "/assets/placeholders/user2avatar.jpg",

        "title": "Grape Ape",

        "imgTopSrc": "https://images-na.ssl-images-amazon.com/images/I/5113xfJXuXL._AC_UL650_SR500,650_QL65_.jpg",
        "imgTopText": "Mens Gorilla Dyed T-Shirt",

        "imgPantsSrc": "https://images-na.ssl-images-amazon.com/images/I/412v4v+CEaL._AC_UL550_SR423,550_QL65_.jpg",
        "imgPantsText": "Rick Owens Men's Drop Crotch Cropped Pants",

        "imgShoesSrc": "https://m.media-amazon.com/images/I/8112-x07qKL._AC_SX255_.jpg",
        "imgShoesText": "New Balance 996v3",

        "postTime": "Mon Nov 22 2021 23:38:47 GMT-0500 (Eastern Standard Time)",

        "caption": "Another fine day",

        "likes": 12,

        "isPublic": true

    }
###
POST http://localhost:3100/posts
Content-Type: application/json
    
    {
        "userHandle": "@fuck_man",
        "firstName": "Pho",
        "lastName": "Man",
        "profilePic": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0876e399-6c27-4b0c-bf43-0ccd01065128/d5c74js-837724c3-6eb5-4b43-8dcf-44ec1c10153c.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA4NzZlMzk5LTZjMjctNGIwYy1iZjQzLTBjY2QwMTA2NTEyOFwvZDVjNzRqcy04Mzc3MjRjMy02ZWI1LTRiNDMtOGRjZi00NGVjMWMxMDE1M2MuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.RA8X7F_0WZac0XwxZ5Z9RcHqY4U7zU7vcUJZA0Ix9cY",

        "title": "Silly Monkey Shirt Outfit",

        "imgTopSrc": "https://images-na.ssl-images-amazon.com/images/I/5113xfJXuXL._AC_UL650_SR500,650_QL65_.jpg",
        "imgTopText": "Mens Gorilla Dyed T-Shirt",

        "imgPantsSrc": "https://images-na.ssl-images-amazon.com/images/I/412v4v+CEaL._AC_UL550_SR423,550_QL65_.jpg",
        "imgPantsText": "Rick Owens Men's Drop Crotch Cropped Pants",

        "imgShoesSrc": "https://m.media-amazon.com/images/I/8112-x07qKL._AC_SX255_.jpg",
        "imgShoesText": "New Balance 996v3",

        "postTime": "Mon Nov 22 2021 23:38:47 GMT-0500 (Eastern Standard Time)",

        "caption": "I stole this outfit from @uruhara_kisuke",

        "likes": 0,

        "isPublic": true

    }
###
http://localhost:3100/posts/wall/@uruhara_kisuke
###
http://localhost:3100/posts/feed/@uruhara_kisuke



###
POST http://localhost:3100/users/seed
###
http://localhost:3100/users
###
http://localhost:3100/users/619c707fb1ea22f2756adc9f
###
http://localhost:3100/users/byhandle/@uruhara_kisuke
###
POST http://localhost:3100/users/register
Content-Type: application/json

    {     
        "firstName": "Pho",
        "lastName": "Man",
        "userHandle": "@fuck_man",
        "password": "fuck",
        "profilePic": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0876e399-6c27-4b0c-bf43-0ccd01065128/d5c74js-837724c3-6eb5-4b43-8dcf-44ec1c10153c.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA4NzZlMzk5LTZjMjctNGIwYy1iZjQzLTBjY2QwMTA2NTEyOFwvZDVjNzRqcy04Mzc3MjRjMy02ZWI1LTRiNDMtOGRjZi00NGVjMWMxMDE1M2MuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.RA8X7F_0WZac0XwxZ5Z9RcHqY4U7zU7vcUJZA0Ix9cY",
        "isAdmin": false,
        "email": "manf@newpaltz.edu",
        "followers": [],
        "following": [ { "handle": "@uruhara_kisuke", "isApproved": true} ]
    }

